# Generated by Django 5.1.4 on 2025-01-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(1, 'Indies'), (2, 'Pugs'), (3, 'German'), (4, 'Bulldog'), (5, 'Labrador'), (6, 'Combai')], verbose_name='Pet Name')),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('vaccination', models.CharField(max_length=100)),
                ('surgery', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, verbose_name='Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Available')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
