# Generated by Django 5.1.4 on 2025-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet_breed',
            field=models.IntegerField(),
        ),
    ]
