# Generated by Django 5.1.4 on 2025-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adoptionrequest_pet_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
