# Generated by Django 5.1.4 on 2025-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_donar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
