# Generated by Django 5.1.4 on 2025-01-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_donar_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donar',
        ),
    ]
