# Generated by Django 5.1.4 on 2025-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.FloatField(),
        ),
    ]
